"""
Workshop Toolkit – Asset Manager Module
Handles TF2 LOD collection structure, registration, duplication, and FBX export.
"""

import bpy
import bmesh
import os
import re
from bpy.props import (
    IntProperty, StringProperty, BoolProperty, EnumProperty
)
from bpy.types import Operator, Panel, PropertyGroup


# ============================================================ #
#                       HELPER FUNCTIONS                       #
# ============================================================ #

LOD_LIMITS = {
    "_lod0": 1400,
    "_lod1": 1000,
    "_lod2": 700,
}


def _tri_count(collection):
    """Return total triangle count across all mesh objects in a collection,
    including geometry generated by modifiers (uses the evaluated depsgraph)."""
    depsgraph = bpy.context.evaluated_depsgraph_get()
    total = 0
    for obj in collection.objects:
        if obj.type != "MESH" or not obj.data:
            continue
        obj_eval = obj.evaluated_get(depsgraph)
        mesh_eval = obj_eval.to_mesh()
        if mesh_eval is None:
            continue
        for poly in mesh_eval.polygons:
            total += poly.loop_total - 2
        obj_eval.to_mesh_clear()
    return total


def get_lod_suffixes(is_library=False):
    if is_library:
        return ["_morphs_low_lod0", "_morphs_low_lod1", "_morphs_low_lod2"]
    return ["_lod0", "_lod1", "_lod2", "_high"]


def sync_visibility(item, suffix_type, value):
    real_suffix = suffix_type
    if item.is_library:
        mapping = {
            "_lod0": "_morphs_low_lod0",
            "_lod1": "_morphs_low_lod1",
            "_lod2": "_morphs_low_lod2",
        }
        real_suffix = mapping.get(suffix_type, suffix_type)
    coll = bpy.data.collections.get(item.name + real_suffix)
    if coll:
        coll.hide_viewport = not value
        coll.hide_render = not value


def collapse_all_collections():
    for window in bpy.context.window_manager.windows:
        for area in window.screen.areas:
            if area.type == "OUTLINER":
                for region in area.regions:
                    if region.type == "WINDOW":
                        with bpy.context.temp_override(
                            window=window, area=area, region=region
                        ):
                            try:
                                bpy.ops.outliner.show_hierarchy(backfill=False)
                            except Exception:
                                pass
                        return


def detect_asset_from_name(name):
    lib_sfx = ["_morphs_low_lod0", "_morphs_low_lod1", "_morphs_low_lod2"]
    std_sfx = ["_lod0", "_lod1", "_lod2", "_high"]
    for s in lib_sfx:
        if s in name:
            return name.split(s)[0], True
    for s in std_sfx:
        if s in name:
            return name.split(s)[0], False
    return None, False


def perform_material_sync(base_name, use_two_mats):
    suffixes = ["_lod0", "_lod1", "_lod2", "_high"]
    for sfx in suffixes:
        coll = bpy.data.collections.get(base_name + sfx)
        if not coll:
            continue
        for obj in coll.objects:
            if obj.type != "MESH":
                continue
            if len(obj.material_slots) > 0 and obj.material_slots[0].material:
                obj.material_slots[0].material.name = f"A_{base_name}"
            if (
                use_two_mats
                and len(obj.material_slots) > 1
                and obj.material_slots[1].material
            ):
                obj.material_slots[1].material.name = f"Z_{base_name}"


def apply_modifiers_with_shapekeys(context, obj, target_collection):
    if not obj.data.shape_keys:
        bpy.ops.object.select_all(action="DESELECT")
        obj.select_set(True)
        context.view_layer.objects.active = obj
        bpy.ops.object.convert(target="MESH")
        return context.view_layer.objects.active

    original_name = obj.name
    original_solo = obj.show_only_shape_key
    original_active_index = obj.active_shape_key_index

    obj.show_only_shape_key = False

    armature_mods = [m for m in obj.modifiers if m.type == "ARMATURE"]
    for m in armature_mods:
        m.show_viewport = False

    depsgraph = context.evaluated_depsgraph_get()
    shape_keys = obj.data.shape_keys.key_blocks
    temp_meshes = []

    for sk in shape_keys:
        sk.value = 0.0

    for i in range(len(shape_keys)):
        sk = shape_keys[i]
        sk.value = 1.0
        obj.active_shape_key_index = i
        context.view_layer.update()

        obj_eval = obj.evaluated_get(depsgraph)
        mesh_eval = bpy.data.meshes.new_from_object(
            obj_eval, preserve_all_data_layers=True, depsgraph=depsgraph
        )
        temp_meshes.append(mesh_eval)
        sk.value = 0.0

    new_mesh_data = temp_meshes[0]
    new_obj = bpy.data.objects.new(original_name + "_applied", new_mesh_data)
    target_collection.objects.link(new_obj)

    # bpy.data.objects.new() defaults to identity transform; the original
    # obj's location/rotation/scale are NOT carried over. Without copying
    # them across, shape-keyed meshes processed by this helper land at
    # the world origin while their non-shape-keyed siblings (handled by
    # the bpy.ops.object.convert path above) keep their transforms — which
    # then produces inconsistent geometry positions after the caller's
    # transform_apply + join + export pipeline.
    new_obj.matrix_world = obj.matrix_world.copy()

    new_obj.shape_key_add(name=shape_keys[0].name)
    for i in range(1, len(temp_meshes)):
        new_sk = new_obj.shape_key_add(name=shape_keys[i].name)
        coords = [0.0] * len(temp_meshes[i].vertices) * 3
        temp_meshes[i].vertices.foreach_get("co", coords)
        new_sk.data.foreach_set("co", coords)
        bpy.data.meshes.remove(temp_meshes[i])

    bpy.data.objects.remove(obj, do_unlink=True)
    new_obj.name = original_name
    new_obj.show_only_shape_key = original_solo
    new_obj.active_shape_key_index = original_active_index

    # NOTE: We deliberately DO NOT re-add the Armature modifier here, even
    # though we removed it earlier (via show_viewport=False during shape
    # key evaluation, then implicit drop via the new_obj rebuild).
    #
    # The non-shape-keyed branch above uses bpy.ops.object.convert which
    # APPLIES every modifier including Armature into the mesh data, so it
    # also returns a modifier-free object. By mirroring that behaviour
    # here we keep the two branches symmetric — both return an unbound
    # mesh — which matters for downstream callers like Quick Export and
    # All-Class. They both immediately strip-then-re-add the Armature
    # modifier with the correct armature, and they BOTH need the mesh to
    # be unbound when transform_apply runs. With the old re-add behaviour,
    # the shape-keyed branch left an Armature mod attached, and a later
    # transform_apply on a still-bound mesh corrupted the bind matrix the
    # FBX exporter writes — non-shape-keyed exports came out correct
    # while shape-keyed exports retained the source variant's spread
    # offset on the armature in the engine.

    return new_obj



def _setup_asset_material_nodes(mat, asset_name):
    """
    Ensure *mat* has a clean Principled BSDF → Output graph and nothing else.
    The normal map subgraph is deliberately NOT added here — it is built only
    after the first bake via _wire_normal_image_to_material(), so the mesh
    shades normally in the viewport until a real bake exists.
    """
    mat.use_nodes = True
    nodes = mat.node_tree.nodes
    links = mat.node_tree.links
    nodes.clear()

    bsdf = nodes.new("ShaderNodeBsdfPrincipled")
    bsdf.location = (0, 0)

    out = nodes.new("ShaderNodeOutputMaterial")
    out.location = (300, 0)
    links.new(bsdf.outputs["BSDF"], out.inputs["Surface"])


def _collect_asset_materials(asset_name):
    """
    Return the list of unique materials actually used by the meshes in
    *asset_name*_lod0, in the order they're encountered. We use this
    instead of guessing 'A_<asset>' / 'Z_<asset>' because the All-Class
    flow renames asset/collection names but deliberately leaves the
    material names alone — every per-class variant shares the same
    materials as the original asset, regardless of what the asset is
    now called.
    """
    coll = bpy.data.collections.get(asset_name + "_lod0")
    if not coll:
        return []
    seen = []
    for obj in coll.objects:
        if obj.type != "MESH":
            continue
        for slot in obj.material_slots:
            if slot.material and slot.material not in seen:
                seen.append(slot.material)
    return seen


def _wire_normal_image_to_material(mat, image):
    """
    Called after a successful bake.  On the first call the full normal map
    subgraph is built and wired into the existing Principled BSDF:

      [Image Texture] → [Normal Map (DirectX, Tangent)] → [Principled BSDF]

    On subsequent calls (re-bakes) the existing Image Texture node is simply
    updated to point at the new image — nothing else changes.
    """
    if not mat or not mat.use_nodes:
        return

    nodes = mat.node_tree.nodes
    links = mat.node_tree.links

    # Check if the subgraph already exists
    img_node = next(
        (n for n in nodes if n.type == "TEX_IMAGE" and n.label == "_asset_normal_tex"),
        None,
    )
    if img_node:
        # Already wired — just swap the image
        img_node.image = image
        return

    # First bake: find the Principled BSDF to anchor position and link
    bsdf = next((n for n in nodes if n.type == "BSDF_PRINCIPLED"), None)
    base_x = bsdf.location.x if bsdf else 0
    base_y = bsdf.location.y if bsdf else 0

    # Normal Map node
    nm = nodes.new("ShaderNodeNormalMap")
    nm.location  = (base_x - 250, base_y - 200)
    nm.label     = "_asset_normal_map"
    nm.space = "TANGENT"

    if hasattr(nm, "convention"):
        # Blender 5.1+: native DirectX mode on the Normal Map node
        nm.convention = "DIRECTX"
        flip_node = None
    else:
        # Blender 5.0 and earlier: invert green via an RGB Curves node
        # placed between the Image Texture and the Normal Map node
        flip_node = nodes.new("ShaderNodeRGBCurve")
        flip_node.location = (base_x - 420, base_y - 200)
        flip_node.label    = "_asset_normal_flip_g"

        # curves[0]=C  curves[1]=G  curves[2]=R  curves[3]=B
        g_curve = flip_node.mapping.curves[1]
        # Default points are (0,0) and (1,1) — move them to invert the channel
        g_curve.points[0].location = (0.0, 1.0)
        g_curve.points[1].location = (1.0, 0.0)
        flip_node.mapping.update()

    # Image Texture node
    img_node = nodes.new("ShaderNodeTexImage")
    img_node.location      = (base_x - 700, base_y - 200)
    img_node.label         = "_asset_normal_tex"
    img_node.interpolation = "Linear"
    img_node.image         = image

    # Wire up
    if flip_node:
        links.new(img_node.outputs["Color"], flip_node.inputs["Color"])
        links.new(flip_node.outputs["Color"], nm.inputs["Color"])
    else:
        links.new(img_node.outputs["Color"], nm.inputs["Color"])
    if bsdf:
        links.new(nm.outputs["Normal"], bsdf.inputs["Normal"])


# ============================================================ #
#                         PROPERTIES                           #
# ============================================================ #

def update_asset_name(self, context):
    old, new = self.old_name, self.name
    if old == "" or old == new:
        return
    for prefix in ["A_", "Z_"]:
        mat = bpy.data.materials.get(f"{prefix}{old}")
        if mat:
            mat.name = f"{prefix}{new}"
    root = bpy.data.collections.get(old)
    if root:
        root.name = new
    suffixes = get_lod_suffixes(is_library=self.is_library)
    for sfx in suffixes:
        coll = bpy.data.collections.get(old + sfx)
        if coll:
            coll.name = new + sfx

    self.old_name = new


class TF2AssetItem(PropertyGroup):
    name: StringProperty(name="Asset Name", update=update_asset_name)
    old_name: StringProperty()
    is_library: BoolProperty(default=False)
    do_export: BoolProperty(
        name="Flag for Export",
        default=False,
        description="Flag this asset to be exported",
    )
    show_lod0: BoolProperty(
        default=True,
        update=lambda s, c: sync_visibility(s, "_lod0", s.show_lod0),
    )
    show_lod1: BoolProperty(
        default=True,
        update=lambda s, c: sync_visibility(s, "_lod1", s.show_lod1),
    )
    show_lod2: BoolProperty(
        default=True,
        update=lambda s, c: sync_visibility(s, "_lod2", s.show_lod2),
    )
    show_high: BoolProperty(
        default=True,
        update=lambda s, c: sync_visibility(s, "_high", s.show_high),
    )
    show_stats: BoolProperty(
        name="Show Stats",
        default=False,
        description="Expand to show triangle counts per LOD",
    )


# ============================================================ #
#                          OPERATORS                           #
# ============================================================ #

class TF2_OT_BakeAssetNormal(Operator):
    """Bake a tangent-space normal map for this asset using its _lod0 and _high collections. Settings are read from the Bake Tools panel."""
    bl_idname  = "tf2.bake_asset_normal"
    bl_label   = "Bake Normal Map"
    bl_options = {"REGISTER", "UNDO"}

    asset_name: StringProperty()

    @classmethod
    def poll(cls, context):
        return bool(context.scene.tf2_assets)

    def execute(self, context):
        from . import bake_tools   # lazy import to avoid circular deps

        props = context.scene.bake_props

        # Gather low meshes from _lod0
        low_coll = bpy.data.collections.get(self.asset_name + "_lod0")
        if not low_coll:
            self.report({"ERROR"},
                        f"Collection '{self.asset_name}_lod0' not found.")
            return {"CANCELLED"}

        low_meshes = [o for o in low_coll.objects
                      if o.type == "MESH"]
        if not low_meshes:
            self.report({"ERROR"},
                        f"No meshes in '{self.asset_name}_lod0'.")
            return {"CANCELLED"}

        # Gather high meshes from _high (optional — self-bake if absent)
        high_coll  = bpy.data.collections.get(self.asset_name + "_high")
        high_meshes = []
        if high_coll:
            high_meshes = [o for o in high_coll.objects
                           if o.type == "MESH"]

        # Force-show all relevant collections and objects for the duration of
        # the bake.  Blender refuses to bake hidden objects/collections, but
        # the user may have them hidden in the asset panel.  We save every
        # hide flag we touch and restore them all in a finally block so the
        # viewport state is always left exactly as the user had it.
        colls_to_show = [c for c in [low_coll, high_coll] if c is not None]
        all_objs      = low_meshes + high_meshes

        # (collection, attr, original_value)
        coll_state = [(c, "hide_viewport", c.hide_viewport) for c in colls_to_show] +                      [(c, "hide_render",   c.hide_render)   for c in colls_to_show]
        # (object, attr, original_value)
        obj_state  = [(o, "hide_viewport", o.hide_viewport) for o in all_objs] +                      [(o, "hide_render",   o.hide_render)   for o in all_objs] +                      [(o, "hide_set",      None)            for o in all_objs]

        try:
            # Unhide collections
            for c in colls_to_show:
                c.hide_viewport = False
                c.hide_render   = False

            # Unhide individual objects (hide_set is the "H" key in viewport)
            for o in all_objs:
                o.hide_viewport = False
                o.hide_render   = False
                o.hide_set(False)

            # Use the same name-matching logic as the manual bake panel:
            # _build_bake_sets pairs each _low with its matching _high(s)
            # by stripping the suffix and comparing base names, so
            # "mesh1_low" only bakes against "mesh1_high" / "mesh1_high.001"
            # and never against "mesh2_high".
            all_meshes = low_meshes + high_meshes
            bake_sets, orphans = bake_tools._build_bake_sets(all_meshes)
            if orphans:
                self.report({"WARNING"},
                            f"HIGHs with no matching LOW (skipped): {', '.join(orphans)}")

            # Group the resulting bake sets by material image name so that:
            #   (a) meshes sharing a material accumulate into one image
            #       (single _run_bake_sets call, use_clear only on first)
            #   (b) we can hide all other-material lows during each group's
            #       bake to prevent cross-material ray projection
            from collections import OrderedDict
            # img_name → list of bake_set dicts
            img_groups = OrderedDict()
            for bset in bake_sets:
                low = bset["low"]
                mat = low.data.materials[0] if low.data.materials and low.data.materials[0] else None
                img_name = f"{mat.name}_normal" if mat else "normal_bake"
                img_groups.setdefault(img_name, []).append(bset)

            # Expose first image name for composite/save buttons.
            # output_name is a StringProperty — safe to set now.
            # composite_base_pick is a dynamic EnumProperty that only accepts
            # values present in bpy.data.images at the moment of assignment,
            # so it must be set AFTER the bake loop creates the image.
            first_img = next(iter(img_groups), "normal_bake")
            props.output_name = first_img

            result = {"FINISHED"}
            for img_name, group_sets in img_groups.items():
                group_lows = [bs["low"] for bs in group_sets]

                # Hide every low NOT in this group via hide_set so the
                # Cycles depsgraph (used by selected-to-active bake) truly
                # excludes them — hide_viewport/render alone is not enough.
                other_lows = [l for l in low_meshes if l not in group_lows]
                saved_hide = [(o, o.hide_viewport, o.hide_render) for o in other_lows]
                for o in other_lows:
                    o.hide_viewport = True
                    o.hide_render   = True
                    o.hide_set(True)

                try:
                    result = bake_tools._run_bake_sets(
                        self, context, group_sets, img_name, props
                    )
                finally:
                    for o, hv, hr in saved_hide:
                        o.hide_viewport = hv
                        o.hide_render   = hr
                        o.hide_set(False)

                if result != {"FINISHED"}:
                    break

            # Now the image exists — safe to set the enum picker.
            if bpy.data.images.get(first_img):
                props.composite_base_pick = first_img

            # Wire each unique material to its correctly-named bake image
            if result == {"FINISHED"}:
                for img_name, group_sets in img_groups.items():
                    baked_img = bpy.data.images.get(img_name)
                    if not baked_img:
                        continue
                    seen_mats = set()
                    for bset in group_sets:
                        for slot in bset["low"].material_slots:
                            if slot.material and slot.material not in seen_mats:
                                _wire_normal_image_to_material(slot.material, baked_img)
                                seen_mats.add(slot.material)

        finally:
            # Restore collection visibility
            for c, attr, val in coll_state:
                setattr(c, attr, val)
            # Restore object visibility
            for o, attr, val in obj_state:
                if attr == "hide_set":
                    pass  # hide_set is write-only; viewport/render flags cover it
                else:
                    setattr(o, attr, val)

        return result


class TF2_OT_QuickExport(Operator):
    """Export all flagged assets as game-ready FBX files to the /mesh/ folder."""
    bl_idname = "tf2.quick_export"
    bl_label = "Quick Export Flagged"
    bl_options = {"REGISTER", "UNDO"}

    def execute(self, context):
        if not bpy.data.is_saved:
            self.report({"ERROR"}, "Save your Blender file first!")
            return {"CANCELLED"}

        project_dir = os.path.dirname(bpy.data.filepath)
        export_dir = os.path.join(project_dir, "mesh")
        if not os.path.exists(export_dir):
            os.makedirs(export_dir)

        export_assets = [item for item in context.scene.tf2_assets if item.do_export]
        if not export_assets:
            self.report({"WARNING"}, "No assets flagged for export!")
            return {"CANCELLED"}

        target_lods = ["_lod0", "_lod1", "_lod2"]
        original_active = context.view_layer.objects.active
        exported_files = 0

        for asset in export_assets:
            real_suffixes = get_lod_suffixes(is_library=asset.is_library)

            # Find the asset's armature once (from any mesh in lod0). Used
            # by every LOD's re-centering step below — not just lod0 — so
            # that every LOD's exported geometry sits at world origin
            # regardless of where the variant is parked in the viewport.
            asset_armature = None
            asset_lod0 = bpy.data.collections.get(asset.name + real_suffixes[0])
            if asset_lod0:
                for obj in asset_lod0.objects:
                    if obj.type == "MESH":
                        for mod in obj.modifiers:
                            if mod.type == "ARMATURE" and mod.object:
                                asset_armature = mod.object
                                break
                    if asset_armature:
                        break

            for i, standard_suffix in enumerate(target_lods):
                if i >= len(real_suffixes):
                    break
                actual_suffix = real_suffixes[i]
                coll_name = asset.name + actual_suffix
                coll = bpy.data.collections.get(coll_name)
                if not coll:
                    continue

                export_coll = bpy.data.collections.new(coll_name + "_temp")
                context.scene.collection.children.link(export_coll)

                # Per-LOD reference to the same armature; only the first LOD
                # actually includes the armature in the export selection.
                target_armature = asset_armature if i == 0 else None

                temp_meshes = []
                for obj in coll.objects:
                    if obj.type != "MESH":
                        continue
                    new_obj = obj.copy()
                    new_obj.data = obj.data.copy()
                    export_coll.objects.link(new_obj)
                    processed_obj = apply_modifiers_with_shapekeys(
                        context, new_obj, export_coll
                    )
                    temp_meshes.append(processed_obj)

                if not temp_meshes:
                    bpy.data.collections.remove(export_coll)
                    continue

                bpy.ops.object.select_all(action="DESELECT")
                for m in temp_meshes:
                    m.select_set(True)
                context.view_layer.objects.active = temp_meshes[0]

                bpy.ops.object.parent_clear(type="CLEAR_KEEP_TRANSFORM")
                bpy.ops.object.transform_apply(location=True, rotation=True, scale=True)
                bpy.ops.object.join()

                final_mesh = context.view_layer.objects.active
                final_mesh.name = coll_name + "_merged"

                # After join, add the armature modifier back.
                # join() keeps only the active object's modifiers and
                # apply_modifiers_with_shapekeys converts/applies all modifiers
                # (including armature) into the mesh data, so the modifier is
                # gone by this point. Re-add it so the FBX exporter sees the
                # mesh correctly bound to the skeleton.
                if target_armature:
                    # Remove any stale armature mods that survived
                    for mod in list(final_mesh.modifiers):
                        if mod.type == "ARMATURE":
                            final_mesh.modifiers.remove(mod)
                    arm_mod = final_mesh.modifiers.new(name="Armature", type="ARMATURE")
                    arm_mod.object = target_armature

                if i == 0 and target_armature:
                    if target_armature.name not in export_coll.objects:
                        export_coll.objects.link(target_armature)
                    target_armature.select_set(True)

                final_mesh.select_set(True)
                fbx_path = os.path.join(export_dir, f"{coll_name}.fbx")

                # ── Re-center for export ────────────────────────────────
                # Shift both the merged mesh and the asset's armature so
                # they end up at world origin in the FBX. The mesh has the
                # variant's All-Class spread (and any other authoring
                # offset) baked into its vertex coords by the earlier
                # transform_apply, and the armature sits at whatever world
                # position the user has it parked at in the scene. Without
                # this step the FBX records both at +X (matching the
                # scene), so when imported standalone — without being
                # re-attached to a player skeleton in the engine — the
                # entire model floats away from origin.
                #
                # Both objects get shifted by the SAME amount — the
                # armature's world translation — so their relative
                # positions don't change and the rigging stays correct.
                # The shift is applied to the mesh by transform_apply
                # (baked into verts) and to the armature by direct
                # matrix_world write, which we restore after export so
                # the user's scene layout is untouched.
                saved_arm_matrix = None
                if asset_armature:
                    offset = asset_armature.matrix_world.translation.copy()
                    if offset.length_squared > 0.0:
                        # Mesh: shift then bake
                        final_mesh.location = final_mesh.location - offset
                        bpy.ops.object.select_all(action="DESELECT")
                        final_mesh.select_set(True)
                        context.view_layer.objects.active = final_mesh
                        bpy.ops.object.transform_apply(
                            location=True, rotation=False, scale=False
                        )
                        # Armature: stash + zero translation
                        saved_arm_matrix = asset_armature.matrix_world.copy()
                        new_mat = saved_arm_matrix.copy()
                        new_mat.translation = (0.0, 0.0, 0.0)
                        asset_armature.matrix_world = new_mat

                        # Re-establish the export selection — the
                        # transform_apply call above wiped it.
                        bpy.ops.object.select_all(action="DESELECT")
                        final_mesh.select_set(True)
                        if i == 0 and target_armature:
                            target_armature.select_set(True)
                        context.view_layer.objects.active = final_mesh

                bpy.ops.export_scene.fbx(
                    filepath=fbx_path,
                    use_selection=True,
                    object_types={"ARMATURE", "MESH"},
                    global_scale=1.0,
                    apply_scale_options="FBX_SCALE_UNITS",
                    axis_forward="-Z",
                    axis_up="Y",
                    bake_anim=False,
                    use_mesh_modifiers=False,
                )
                exported_files += 1

                # Restore the armature's scene position. The mesh was a
                # throwaway temp in export_coll; it gets removed below
                # along with the rest of the temp collection contents,
                # so its baked-in shift is forgotten naturally.
                if saved_arm_matrix is not None:
                    asset_armature.matrix_world = saved_arm_matrix

                if i == 0 and target_armature:
                    export_coll.objects.unlink(target_armature)

                for o in list(export_coll.objects):
                    if o.type == "MESH":
                        data = o.data
                        bpy.data.objects.remove(o, do_unlink=True)
                        if data.users == 0:
                            bpy.data.meshes.remove(data)
                    else:
                        bpy.data.objects.remove(o, do_unlink=True)

                bpy.data.collections.remove(export_coll)

        if original_active:
            context.view_layer.objects.active = original_active
        self.report({"INFO"}, f"TF2 Export Complete: {exported_files} files exported.")
        return {"FINISHED"}


class TF2_OT_RegisterSelected(Operator):
    """Register the selected object or collection as a tracked asset."""
    bl_idname = "tf2.register_selected"
    bl_label = "Register Asset"
    asset_name: StringProperty(name="Detected Asset")
    is_lib: BoolProperty()
    do_sync: BoolProperty(name="Sync Material Names?", default=True)
    two_mats: BoolProperty(name="Use Two Materials? (A/Z)", default=False)

    def draw(self, context):
        layout = self.layout
        layout.prop(self, "asset_name")
        box = layout.box()
        box.prop(self, "do_sync")
        sub = box.row()
        sub.active = self.do_sync
        sub.prop(self, "two_mats")

    def execute(self, context):
        if not any(item.name == self.asset_name for item in context.scene.tf2_assets):
            new_item = context.scene.tf2_assets.add()
            new_item.name = self.asset_name
            new_item.old_name = self.asset_name
            new_item.is_library = self.is_lib
        if not self.is_lib and self.do_sync:
            perform_material_sync(self.asset_name, self.two_mats)
        collapse_all_collections()
        return {"FINISHED"}

    def invoke(self, context, event):
        potential_names = set()
        if context.collection:
            potential_names.add(context.collection.name)
        for obj in context.selected_objects:
            potential_names.add(obj.name)
            for coll in obj.users_collection:
                potential_names.add(coll.name)

        target_base, target_lib = None, False
        for p_name in potential_names:
            base, is_lib = detect_asset_from_name(p_name)
            if not base:
                root = bpy.data.collections.get(p_name)
                if root:
                    for child in root.children:
                        b, lib = detect_asset_from_name(child.name)
                        if b:
                            base, is_lib = b, lib
                            break
            if not base:
                base = p_name
            test_sfx = "_morphs_low_lod0" if is_lib else "_lod0"
            if bpy.data.collections.get(base + test_sfx):
                target_base, target_lib = base, is_lib
                break

        if not target_base:
            return {"CANCELLED"}
        self.asset_name, self.is_lib = target_base, target_lib
        if not self.is_lib:
            return context.window_manager.invoke_props_dialog(self)
        return self.execute(context)


class TF2_OT_InitializeAsset(Operator):
    """Create a new asset with lod0/lod1/lod2/high collections and a starter material."""
    bl_idname = "tf2.initialize_asset"
    bl_label = "Initialize TF2 Asset"
    asset_name: StringProperty(name="Asset Name", default="cosmetic")
    use_two_mats: BoolProperty(name="Create Two Materials?", default=False)

    def _unique_name(self, base):
        """Strip any trailing _N suffix, then find the next free name."""
        base = re.sub(r"_\d+$", "", base)
        existing = {i.name for i in bpy.context.scene.tf2_assets}
        existing |= {c.name for c in bpy.data.collections}
        if base not in existing:
            return base
        index = 2
        while f"{base}_{index}" in existing:
            index += 1
        return f"{base}_{index}"

    def invoke(self, context, event):
        # Pre-fill with a guaranteed-unique name so the dialog already shows it
        self.asset_name = self._unique_name(self.asset_name)
        return context.window_manager.invoke_props_dialog(self)

    def execute(self, context):
        name = self.asset_name
        a_mat  = bpy.data.materials.new(name=f"A_{name}")
        _setup_asset_material_nodes(a_mat, name)
        mats = [a_mat]
        if self.use_two_mats:
            mats.append(bpy.data.materials.new(name=f"Z_{name}"))
        configs = [
            (f"{name}_lod0", "COLOR_05"),
            (f"{name}_lod1", "COLOR_05"),
            (f"{name}_lod2", "COLOR_05"),
            (f"{name}_high", "COLOR_06"),
        ]
        for c_name, c_color in configs:
            new_col = bpy.data.collections.new(c_name)
            context.scene.collection.children.link(new_col)
            new_col.color_tag = c_color
        new_item = context.scene.tf2_assets.add()
        new_item.name, new_item.old_name = name, name
        collapse_all_collections()
        return {"FINISHED"}


class TF2_OT_DuplicateAsset(Operator):
    bl_idname = "tf2.duplicate_asset"
    bl_label = "Duplicate Asset Variation"
    asset_name: StringProperty()
    create_new_mats: BoolProperty(name="Create New Materials?", default=False)

    def execute(self, context):
        base_item = next(
            i for i in context.scene.tf2_assets if i.name == self.asset_name
        )
        base_name = self.asset_name
        indices = [0]
        for c in bpy.data.collections:
            match = re.search(rf"{re.escape(base_name)}_s(\d+)_lod0", c.name)
            if match:
                indices.append(int(match.group(1)))
        next_idx = max(indices) + 1
        new_base = f"{base_name}_s{next_idx}"
        mat_map = {}
        if self.create_new_mats:
            for p in ["A_", "Z_"]:
                old = bpy.data.materials.get(f"{p}{base_name}")
                if old:
                    new = old.copy()
                    new.name = f"{p}{new_base}"
                    mat_map[old] = new
        suffixes = get_lod_suffixes(is_library=base_item.is_library)
        if "_high" in suffixes:
            suffixes.remove("_high")
        for sfx in suffixes:
            source = bpy.data.collections.get(base_name + sfx)
            if not source:
                continue
            new_col = bpy.data.collections.new(new_base + sfx)
            context.scene.collection.children.link(new_col)
            new_col.color_tag = source.color_tag
            for o in source.objects:

                new_o = o.copy()
                if o.type != "ARMATURE" and o.data:
                    new_o.data = o.data.copy()
                new_col.objects.link(new_o)
                if self.create_new_mats:
                    for slot in new_o.material_slots:
                        if slot.material in mat_map:
                            slot.material = mat_map[slot.material]
        new_item = context.scene.tf2_assets.add()
        new_item.name = new_base
        new_item.old_name = new_base
        new_item.is_library = base_item.is_library
        collapse_all_collections()
        return {"FINISHED"}

    def invoke(self, context, event):
        return context.window_manager.invoke_props_dialog(self)


class TF2_OT_RemoveAsset(Operator):
    bl_idname = "tf2.remove_asset"
    bl_label = "Confirm Deletion"
    index: IntProperty()
    asset_name: StringProperty()

    def execute(self, context):
        for c in list(bpy.data.collections):
            if c.name.startswith(self.asset_name):
                for o in list(c.objects):
                    bpy.data.objects.remove(o, do_unlink=True)
                bpy.data.collections.remove(c)
        context.scene.tf2_assets.remove(self.index)
        return {"FINISHED"}

    def invoke(self, context, event):
        return context.window_manager.invoke_confirm(self, event)


# ============================================================ #
#                  ALL-CLASS GENERATION                        #
# ============================================================ #

TF2_CLASSES = (
    "scout", "soldier", "pyro", "demo", "heavy",
    "engineer", "medic", "sniper", "spy",
)


def _detect_class_from_armature(arm_obj):
    """Return the class name parsed from an armature named '<class>_ARM',
    or None if the armature name doesn't match the pattern or the prefix
    isn't a known TF2 class."""
    if not arm_obj or arm_obj.type != "ARMATURE":
        return None
    name = arm_obj.name
    if not name.endswith("_ARM"):
        return None
    prefix = name[:-len("_ARM")].lower()
    if prefix in TF2_CLASSES:
        return prefix
    return None


def _find_armature_in_collection(coll):
    """Return the first armature referenced by an Armature modifier on any
    mesh in *coll*, or None."""
    if not coll:
        return None
    for obj in coll.objects:
        if obj.type != "MESH":
            continue
        for mod in obj.modifiers:
            if mod.type == "ARMATURE" and mod.object:
                return mod.object
    return None


def _get_target_assets_enum(self, context):
    items = []
    for item in context.scene.tf2_assets:
        if not item.is_library:
            items.append((item.name, item.name, ""))
    if not items:
        items.append(("NONE", "No registered assets", ""))
    return items


LATTICE_NAME_SUFFIX = "_lattice"


def _find_existing_lattice(asset_name):
    """
    Return the lattice object dedicated to *asset_name*, or None.

    We name lattices `<asset_name>_lattice` and create exactly one per
    class variant. The lookup is by object-name only — we don't scan the
    asset's collections, since teardown re-homes lattices to the scene
    root collection when LOD collections are wiped.
    """
    obj = bpy.data.objects.get(asset_name + LATTICE_NAME_SUFFIX)
    if obj and obj.type == "LATTICE":
        return obj
    return None


def _bind_lattice_modifier(mesh_obj, lattice_obj):
    """
    Attach a Lattice modifier on *mesh_obj* pointing at *lattice_obj*.
    Strips any prior Lattice modifiers first so re-binding doesn't pile
    them up across refreshes. Named "Lattice" so it shows up predictably
    in the modifier stack.
    """
    for mod in list(mesh_obj.modifiers):
        if mod.type == "LATTICE":
            mesh_obj.modifiers.remove(mod)
    mod = mesh_obj.modifiers.new(name="Lattice", type="LATTICE")
    mod.object = lattice_obj
    return mod


def _bip_head_local_pos(arm_obj):
    """
    Return the rest-pose position of the 'bip_head' bone in armature-local
    space (i.e. relative to the armature's own origin), or None if the
    armature has no such bone.

    We deliberately use the LOCAL position rather than world space: the
    All-Class flow needs to compare bip_head positions across different
    class armatures purely as a "how tall is this character" measurement.
    Using world space would also pick up wherever the user has parked each
    armature in the viewport — and since people often spread their class
    armatures out on X for visual inspection, that armature placement
    would leak into the head-alignment delta and shift hats sideways
    instead of just up/down. Local space is invariant to armature
    placement: scout_bip_head.head_local stays the same whether scout_ARM
    sits at world (0,0,0) or (500,0,0).
    """
    if not arm_obj or arm_obj.type != "ARMATURE":
        return None
    bone = arm_obj.data.bones.get("bip_head")
    if bone is None:
        return None
    return bone.head_local.copy()


def _strip_class_prefix(asset_name):
    """If *asset_name* starts with one of the TF2 class prefixes, return
    (prefix, base). Otherwise return (None, asset_name)."""
    lower = asset_name.lower()
    for cls in TF2_CLASSES:
        if lower.startswith(cls + "_"):
            return cls, asset_name[len(cls) + 1:]
    return None, asset_name


def _teardown_class_variant(asset_name, lod_suffixes):
    """
    Remove the LOD collections (and their contained mesh objects + orphaned
    mesh data) for a class-variant asset. Used by All-Class refresh so we
    can rebuild from the current source without leaking duplicate meshes.
    Only collections matching `<asset_name><sfx>` exactly are touched.

    Lattice objects (type == "LATTICE") are deliberately skipped: the user
    may have spent significant effort sculpting them, and the All-Class
    operator's lattice toggle treats existing lattices as "carry over and
    re-bind". They are unlinked from the doomed collection and re-homed
    into the scene root collection so they survive the rebuild and can be
    re-linked into the fresh _lod0 collection by the rebuild step.
    """
    scene_coll = bpy.context.scene.collection
    for sfx in lod_suffixes:
        coll = bpy.data.collections.get(asset_name + sfx)
        if not coll:
            continue
        for obj in list(coll.objects):
            if obj.type == "LATTICE":
                # Spare the lattice — re-home it to scene root so it
                # outlives the collection removal below.
                coll.objects.unlink(obj)
                if scene_coll.objects.find(obj.name) == -1:
                    scene_coll.objects.link(obj)
                continue
            data = obj.data if obj.type == "MESH" else None
            bpy.data.objects.remove(obj, do_unlink=True)
            if data is not None and data.users == 0:
                bpy.data.meshes.remove(data)
        bpy.data.collections.remove(coll)


class TF2_OT_AllClassGenerate(Operator):
    """Generate or refresh per-class LOD variants of the selected asset, head-aligned to each TF2 class armature."""
    bl_idname  = "tf2.allclass_generate"
    bl_label   = "Generate All-Class Variants"
    bl_options = {"REGISTER", "UNDO"}

    asset_name: EnumProperty(
        name="Source Asset",
        items=_get_target_assets_enum,
    )

    create_lattices: BoolProperty(
        name="Create Lattices",
        default=True,
        description=(
            "Spawn a 3x3x3 B-spline lattice fitted around each variant's "
            "LOD meshes (lod0/lod1/lod2 share one lattice per class). "
            "Existing lattices are always preserved on refresh — toggle "
            "this off if you've already shaped the lattices and just want "
            "to rebuild geometry without disturbing them"
        ),
    )

    @classmethod
    def poll(cls, context):
        return any(not i.is_library for i in context.scene.tf2_assets)

    def invoke(self, context, event):
        non_lib = [i.name for i in context.scene.tf2_assets if not i.is_library]
        if not non_lib:
            self.report({"ERROR"}, "No registered non-library assets found.")
            return {"CANCELLED"}
        return context.window_manager.invoke_props_dialog(self)

    def execute(self, context):
        scene = context.scene

        if not self.asset_name or self.asset_name == "NONE":
            self.report({"ERROR"}, "No asset selected.")
            return {"CANCELLED"}

        src_item = next(
            (i for i in scene.tf2_assets if i.name == self.asset_name),
            None,
        )
        if src_item is None:
            self.report({"ERROR"}, f"Asset '{self.asset_name}' not found.")
            return {"CANCELLED"}
        if src_item.is_library:
            self.report({"ERROR"}, "Library assets are not supported.")
            return {"CANCELLED"}

        # Resolve the source asset's class via its armature
        src_lod0 = bpy.data.collections.get(self.asset_name + "_lod0")
        if src_lod0 is None:
            self.report({"ERROR"},
                        f"Source collection '{self.asset_name}_lod0' not found.")
            return {"CANCELLED"}

        src_arm = _find_armature_in_collection(src_lod0)
        if src_arm is None:
            self.report({"ERROR"},
                        "Source asset has no Armature modifier — can't detect class.")
            return {"CANCELLED"}

        src_class = _detect_class_from_armature(src_arm)
        if src_class is None:
            self.report({"ERROR"},
                        f"Armature '{src_arm.name}' isn't named '<class>_ARM' "
                        f"with a known TF2 class.")
            return {"CANCELLED"}

        # Determine the shared base name (without any class prefix)
        existing_prefix, base_name = _strip_class_prefix(self.asset_name)

        # Rename source collections + asset entry to carry the class prefix.
        # Material names are deliberately left alone — every variant shares
        # the A_/Z_ materials of the original asset.
        if existing_prefix is None:
            new_src_name = f"{src_class}_{base_name}"
            old_src_name = self.asset_name

            # Skip rename if the target name is already taken (collection
            # collision shouldn't ever happen, but guard anyway)
            if (bpy.data.collections.get(new_src_name + "_lod0")
                    and new_src_name != old_src_name):
                self.report({"WARNING"},
                            f"Collection '{new_src_name}_lod0' already exists — "
                            f"leaving source name as '{old_src_name}'.")
            else:
                # Rename collections directly, bypassing update_asset_name's
                # material-rename behaviour by setting old_name first.
                for sfx in get_lod_suffixes(is_library=False):
                    coll = bpy.data.collections.get(old_src_name + sfx)
                    if coll:
                        coll.name = new_src_name + sfx
                src_item.old_name = new_src_name   # suppress material rename
                src_item.name     = new_src_name
                self.asset_name   = new_src_name

        else:
            # Already has a class prefix; require it match the detected class
            if existing_prefix != src_class:
                self.report({"WARNING"},
                            f"Asset name prefix '{existing_prefix}_' doesn't "
                            f"match detected class '{src_class}'. Continuing "
                            f"with detected class.")

        # ── Build per-class variants ───────────────────────────────── #
        other_classes = [c for c in TF2_CLASSES if c != src_class]

        created  = 0
        refreshed = 0
        no_armat = []
        no_head  = []     # classes whose armature lacks a 'bip_head' bone

        # X-offset stride between class variants in the viewport
        OFFSET_X = 50.0

        # Resolve the source class's bip_head position once. This is the
        # reference point the geometry was authored against, so each
        # variant's head-alignment offset is (target_bip_head - this).
        # If the source armature has no bip_head we fall back to no
        # head-alignment at all (variants get only the X-spread offset).
        src_head_pos = _bip_head_local_pos(src_arm)
        if src_head_pos is None:
            self.report({"WARNING"},
                        f"Source armature '{src_arm.name}' has no 'bip_head' bone — "
                        f"variants will not be height-corrected.")

        # Stash original active/selection so we can restore at the end
        prev_active = context.view_layer.objects.active
        prev_sel    = list(context.selected_objects)

        target_lods = ["_lod0", "_lod1", "_lod2"]

        try:
            for slot_idx, cls_name in enumerate(other_classes):
                target_arm_name = f"{cls_name}_ARM"
                target_arm = bpy.data.objects.get(target_arm_name)
                if target_arm is None or target_arm.type != "ARMATURE":
                    no_armat.append(cls_name)
                    continue

                new_asset_name = f"{cls_name}_{base_name}"

                # Per-class head-alignment delta. Only meaningful when both
                # the source and target armatures have a 'bip_head' bone.
                # If either is missing we leave the variant at the source's
                # geometric position and warn the user.
                head_delta = None
                if src_head_pos is not None:
                    tgt_head_pos = _bip_head_local_pos(target_arm)
                    if tgt_head_pos is None:
                        no_head.append(cls_name)
                    else:
                        head_delta = tgt_head_pos - src_head_pos

                # Detect whether this class variant already exists. If any
                # of its LOD collections is present we treat it as a refresh:
                # tear the old collections down (keeping the asset entry)
                # and rebuild from the current source.
                already_exists = any(
                    bpy.data.collections.get(new_asset_name + sfx) is not None
                    for sfx in target_lods
                )
                if already_exists:
                    _teardown_class_variant(new_asset_name, target_lods)
                    refreshed += 1
                else:
                    created += 1

                # Build empty target collections (LOD0/1/2 only; no _high)
                new_colls = {}
                for sfx in target_lods:
                    nc = bpy.data.collections.new(new_asset_name + sfx)
                    scene.collection.children.link(nc)
                    src_coll = bpy.data.collections.get(self.asset_name + sfx)
                    if src_coll:
                        nc.color_tag = src_coll.color_tag
                    new_colls[sfx] = nc

                # Per-class viewport X offset. Pure object-space stride;
                # we deliberately do NOT compensate for where the user has
                # placed the per-class armatures. The visible spread will
                # appear correct when armatures share a position (or sit
                # at world origin); if armatures are themselves spread out
                # AND in pose mode, the rigged-mesh inheritance will add
                # to this — toggle Pose to Rest with the F4 hotkey or
                # park armatures at origin if a clean stride matters more
                # than your inspection layout.
                # +1 on slot_idx so the source variant sits at x_offset 0
                # and the others march outward.
                x_offset = OFFSET_X * (slot_idx + 1)

                # Merge each LOD: copy → apply mods+shape keys → join
                for sfx in target_lods:
                    src_coll = bpy.data.collections.get(self.asset_name + sfx)
                    if not src_coll:
                        continue

                    target_coll = new_colls[sfx]
                    is_lod0     = (sfx == "_lod0")

                    # 1. Duplicate every mesh into the target collection
                    temp_meshes = []
                    for obj in src_coll.objects:
                        if obj.type != "MESH":
                            continue
                        new_o = obj.copy()
                        new_o.data = obj.data.copy()
                        target_coll.objects.link(new_o)
                        # Apply modifiers / shape keys (this re-creates the
                        # object inside target_coll for shape-keyed meshes)
                        processed = apply_modifiers_with_shapekeys(
                            context, new_o, target_coll
                        )
                        temp_meshes.append(processed)

                    if not temp_meshes:
                        continue

                    # 2. Join all temps into one
                    bpy.ops.object.select_all(action="DESELECT")
                    for m in temp_meshes:
                        m.select_set(True)
                    context.view_layer.objects.active = temp_meshes[0]
                    bpy.ops.object.parent_clear(type="CLEAR_KEEP_TRANSFORM")
                    # Apply transforms BEFORE join so any pre-existing object
                    # offsets on source meshes get baked into geometry — this
                    # matches Quick Export. The per-class X-offset we add
                    # AFTER the join is a fresh, unapplied object translation.
                    bpy.ops.object.transform_apply(
                        location=True, rotation=True, scale=True
                    )
                    if len(temp_meshes) > 1:
                        bpy.ops.object.join()

                    final = context.view_layer.objects.active
                    final.name = new_asset_name + sfx + "_merged"

                    # 3. Re-bind armature for lod0 only.
                    # apply_modifiers_with_shapekeys bakes ALL modifiers into
                    # the mesh data (including armature deformation), so any
                    # surviving armature mod from the copy needs to be wiped
                    # before we attach the per-class one.
                    for mod in list(final.modifiers):
                        if mod.type == "ARMATURE":
                            final.modifiers.remove(mod)
                    if is_lod0:
                        arm_mod = final.modifiers.new(name="Armature",
                                                      type="ARMATURE")
                        arm_mod.object = target_arm

                    # 4. Apply head-alignment delta to GEOMETRY (transform-
                    # applied), so the mesh sits at the target class's head
                    # height. The previous transform_apply call left the
                    # object at identity, so we can drop the delta straight
                    # into .location and bake it into the mesh data.
                    if head_delta is not None:
                        final.location = head_delta
                        bpy.ops.object.select_all(action="DESELECT")
                        final.select_set(True)
                        context.view_layer.objects.active = final
                        bpy.ops.object.transform_apply(
                            location=True, rotation=False, scale=False
                        )

                    # 5. Apply per-class viewport X offset (object location
                    # only — NOT applied — so the variants are visually
                    # spread out without affecting the actual mesh data
                    # that gets exported).
                    final.location.x += x_offset

                # ── Lattice step ─────────────────────────────────────── #
                # One shared lattice per class variant, fitted to the
                # combined bbox of all LOD meshes. Three behaviours:
                #
                #   1. Existing lattice (regardless of toggle):
                #      Re-link it into _lod0 if needed, re-bind a fresh
                #      Lattice modifier on each LOD mesh. Lattice points
                #      are preserved (we never recreate the data).
                #
                #   2. No lattice + toggle ON:
                #      Spawn a new 3x3x3 B-spline lattice via the built-in
                #      operator with selection set to all LOD meshes — it
                #      auto-fits and auto-adds modifiers in one call.
                #
                #   3. No lattice + toggle OFF:
                #      Skip — no lattice for this asset.
                lod_meshes = []
                for sfx in target_lods:
                    coll = bpy.data.collections.get(new_asset_name + sfx)
                    if not coll:
                        continue
                    for o in coll.objects:
                        if o.type == "MESH":
                            lod_meshes.append(o)

                if lod_meshes:
                    existing_lattice = _find_existing_lattice(new_asset_name)
                    lod0_coll = new_colls.get("_lod0")

                    if existing_lattice is not None:
                        # Reuse path: home it back into _lod0 if it ended
                        # up loose in the scene root (teardown re-homes
                        # lattices there to keep them alive), then re-bind
                        # the modifier on every LOD mesh.
                        if (lod0_coll is not None
                                and lod0_coll.objects.find(existing_lattice.name) == -1):
                            for parent_coll in list(existing_lattice.users_collection):
                                parent_coll.objects.unlink(existing_lattice)
                            lod0_coll.objects.link(existing_lattice)
                        for m in lod_meshes:
                            _bind_lattice_modifier(m, existing_lattice)

                    elif self.create_lattices:
                        # Fresh-spawn path: select the LOD meshes and let
                        # the built-in lattice_add_to_selected fit the
                        # lattice and add modifiers in one shot. The 3x3x3
                        # resolution is set at create time; the B-spline
                        # interpolation is set on the lattice data after.
                        bpy.ops.object.select_all(action="DESELECT")
                        for m in lod_meshes:
                            m.select_set(True)
                        context.view_layer.objects.active = lod_meshes[0]
                        bpy.ops.object.lattice_add_to_selected(
                            fit_to_selected=True,
                            add_modifiers=True,
                            resolution_u=3,
                            resolution_v=3,
                            resolution_w=3,
                        )

                        # The freshly created lattice is now active.
                        new_lattice = context.view_layer.objects.active
                        if new_lattice and new_lattice.type == "LATTICE":
                            new_lattice.name = new_asset_name + LATTICE_NAME_SUFFIX
                            # Switch all three axes to B-spline
                            new_lattice.data.interpolation_type_u = "KEY_BSPLINE"
                            new_lattice.data.interpolation_type_v = "KEY_BSPLINE"
                            new_lattice.data.interpolation_type_w = "KEY_BSPLINE"
                            # The operator drops the lattice into the
                            # active collection (usually scene root). Move
                            # it into _lod0 alongside the meshes for tidy
                            # outliner organisation.
                            if lod0_coll is not None:
                                for parent_coll in list(new_lattice.users_collection):
                                    parent_coll.objects.unlink(new_lattice)
                                lod0_coll.objects.link(new_lattice)

                # Register the new asset entry only if one isn't already
                # tracking this name (refresh keeps the existing entry).
                if not any(it.name == new_asset_name for it in scene.tf2_assets):
                    new_item = scene.tf2_assets.add()
                    new_item.name     = new_asset_name
                    new_item.old_name = new_asset_name
                    new_item.is_library = False

        finally:
            bpy.ops.object.select_all(action="DESELECT")
            for o in prev_sel:
                try:
                    o.select_set(True)
                except Exception:
                    pass
            if prev_active:
                try:
                    context.view_layer.objects.active = prev_active
                except Exception:
                    pass
            collapse_all_collections()

        # Build a single info report
        msgs = []
        if created:
            msgs.append(f"created {created}")
        if refreshed:
            msgs.append(f"refreshed {refreshed}")
        if not msgs:
            msgs.append("nothing to do")
        report_line = f"All-Class: {', '.join(msgs)}"
        if no_armat:
            report_line += f" | no '<class>_ARM' for: {', '.join(no_armat)}"
        if no_head:
            report_line += f" | no 'bip_head' on: {', '.join(no_head)}"
        self.report({"INFO"}, report_line)
        return {"FINISHED"}


# ============================================================ #
#                            PANEL                             #
# ============================================================ #

class TF2_OT_LODStatsTip(Operator):
    """Show detailed triangle stats for a single LOD"""
    bl_idname  = "tf2.lod_stats_tip"
    bl_label   = ""
    bl_options = {"INTERNAL"}

    asset_name: StringProperty()
    lod_suffix: StringProperty()   # e.g. "_lod0"

    @classmethod
    def description(cls, context, props):
        limit = LOD_LIMITS.get(props.lod_suffix)
        coll  = bpy.data.collections.get(props.asset_name + props.lod_suffix)
        if coll is None:
            return f"LOD{props.lod_suffix[-1]} — collection not found"
        count = _tri_count(coll)
        if limit is None:
            return f"LOD{props.lod_suffix[-1]} — {count:,} tris"
        pct    = 100.0 * count / limit
        over   = count > limit
        status = f"OVER LIMIT by {count - limit:,}" if over else f"{limit - count:,} remaining"
        return f"LOD{props.lod_suffix[-1]}  —  {count:,} / {limit:,} tris  ({pct:.0f}%)  |  {status}"

    def execute(self, context):
        return {"FINISHED"}


class TF2_PT_MainPanel(Panel):
    bl_label = "Workshop Asset Manager"
    bl_idname = "TF2_PT_MainPanel"
    bl_space_type = "VIEW_3D"
    bl_region_type = "UI"
    bl_category = "WS Toolkit"

    def draw(self, context):
        layout = self.layout
        scene = context.scene

        row = layout.row(align=True)
        row.operator("tf2.initialize_asset", text="Initialize", icon="PLAY")
        row.operator("tf2.allclass_generate", text="All-Class", icon="COMMUNITY")
        row.operator("tf2.quick_export", text="Export Flagged", icon="EXPORT")
        row.operator("tf2.register_selected", text="", icon="FILE_REFRESH")
        layout.separator()

        for index, item in enumerate(scene.tf2_assets):
            row = layout.row(align=True)

            if not item.is_library:
                row.prop(
                    item, "show_stats", text="", emboss=False,
                    icon="TRIA_DOWN" if item.show_stats else "TRIA_RIGHT",
                )
            else:
                row.label(text="", icon="BLANK1")

            row.prop(item, "do_export", text="", icon="EXPORT", toggle=True)
            row.operator("tf2.duplicate_asset", text="", icon="ADD").asset_name = item.name

            has_lod0 = bpy.data.collections.get(item.name + "_lod0") is not None
            has_high = bpy.data.collections.get(item.name + "_high") is not None
            if has_lod0 and hasattr(scene, "bake_props"):
                op = row.operator("tf2.bake_asset_normal", text="", icon="IMAGE_DATA")
                op.asset_name = item.name
                if not has_high:
                    row.label(text="", icon="INFO")

            split = row.split(factor=0.55, align=True)
            split.prop(item, "name", text="")
            btn_row = split.row(align=True)
            for i in range(3):
                btn_row.prop(item, f"show_lod{i}", toggle=True, text=str(i))
            if not item.is_library and has_high:
                btn_row.prop(item, "show_high", toggle=True, text="H")
            else:
                btn_row.label(text="", icon="BLANK1")
            btn_row.separator(factor=1.5)
            del_op = btn_row.operator("tf2.remove_asset", text="", icon="TRASH")
            del_op.index, del_op.asset_name = index, item.name

            # ── Expandable stats row ──────────────────────────────────── #
            if not item.is_library and item.show_stats:
                stats_row = layout.row(align=True)
                stats_row.scale_y = 0.7
                stats_row.alignment = "RIGHT"
                for suffix, limit_val in LOD_LIMITS.items():
                    coll = bpy.data.collections.get(item.name + suffix)
                    if coll is None:
                        continue
                    count = _tri_count(coll)
                    over  = count > limit_val
                    op = stats_row.operator(
                        "tf2.lod_stats_tip",
                        text=f"{count:,}/{limit_val:,}",
                        icon="ERROR" if over else "CHECKMARK",
                        emboss=False,
                    )
                    op.asset_name = item.name
                    op.lod_suffix = suffix


# ============================================================ #
#                       REGISTRATION                           #
# ============================================================ #

classes = (
    TF2AssetItem,
    TF2_OT_RegisterSelected,
    TF2_OT_InitializeAsset,
    TF2_OT_DuplicateAsset,
    TF2_OT_RemoveAsset,
    TF2_OT_AllClassGenerate,
    TF2_OT_QuickExport,
    TF2_OT_BakeAssetNormal,
    TF2_OT_LODStatsTip,
    TF2_PT_MainPanel,
)


def register():
    for cls in classes:
        bpy.utils.register_class(cls)


def unregister():
    for cls in reversed(classes):
        bpy.utils.unregister_class(cls)
